[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Timeout for the main vocabulary function
[functions."get-topic-vocabulary"]
  timeout = 90

# Added timeout for the sentence function
[functions."get-sentence"]
  timeout = 90

[dev]
  command = "npm run dev"
  targetPort = 8081
  port = 8888
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 