[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  
[functions."get-topic-vocabulary"]
  timeout = 40

[dev]
  command = "npm run dev"
  targetPort = 8081
  port = 8888
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 